#!/usr/bin/python3
from time import sleep
import RPi.GPIO as GPIO
from pi_sht1x import SHT1x #importing the library in which the functions called in main() are defined, in /usr/local/lib/python3.4
import pymysql #connecting to mysql database with pymysql command (mysql won't work with python3)
pymysql.install_as_MySQLdb() 


DATA_PIN = 18   #Raspberry GPIO pins used to connect the SHT15
SCK_PIN = 23
#connecting to mysql database with pymysql 
conn = pymysql.connect("localhost","root","Australia57","WeatherData")


def main():
   # using default values: 3.5V, High resolution, no heater, otp_no_reload off, CRC checking enabled... A calibration needs to be done.
    with SHT1x(DATA_PIN, SCK_PIN, gpio_mode=GPIO.BCM) as sensor:

 # the next step is write the time simultaneously to keep tracks of the datatime
        temp = sensor.read_temperature() 
        humidity = sensor.read_humidity(temp)
        dewp = sensor.calculate_dew_point(temp, humidity)
        print(sensor) # display the measures in the terminal
        c = conn.cursor()
        c.execute("INSERT INTO Temperature_Humidity(Temperature,Humidity,DewPoint) VALUES('%s','%s','%s')", (temp,humidity,dewp))
        conn.commit() # store data into mysql database named Measurements, in the SHT15 table

if __name__ == "__main__":
    main()
